### ISSUE TITLE
Static report: make one wrapper function

### ISSUE THREAD

**Issue by atn38** [IMCR-Hackathon/ggplotgui#14]
This function will take the ingested and user-selected data entity (with data+metadata list structure) and generate a report. This function is a wrapper for all functions Static Team created.

On the GUI tab for data summary, either this function will execute on load or a button will activate the function.

**Comment by sheilasaia** [comment]
More info about using the `here` package for defining paths (that are agnostic of operating system), see this blog post: https://malco.io/2018/11/05/why-should-i-use-the-here-package/

**Comment by jhp7e** [comment]
For the plot of time vs all the numerical variables which is too large for the space allocated in the report.  That might be better handled in a separate markdown chunk towards the end of the report . As a separate chunk you could make the graphs larger to accommodate that large, complex task.
