### ISSUE TITLE
Merge the ui and server into a single function

### ISSUE THREAD

**Issue by wetlandscapes** [IMCR-Hackathon/ggplotgui#27]
Though I don't usually like having a single massive function, in the context of shiny apps it seems to make a bit more sense.

Further, once we merge everything together into a single function then we can treat the app like any other function, and move it into the R folder, give it a Roxygen2 skeleton, etc.

**Comment by clnsmth** [comment]
This issue is related to  #7

**Comment by ktoddbrown** [comment]
Done in PR #39 #38 #37 #35 Everything seems to work as well as it did before hand. Documentation is still needed.

**Comment by wetlandscapes** [comment]
Impressive!

**Comment by sheilasaia** [comment]
@wetlandscapes and @ktoddbrown can we close this or are we still working on documentation?
