### ISSUE TITLE
Display static report as html in gui

### ISSUE THREAD

**Issue by wetlandscapes** [IMCR-Hackathon/ggplotgui#32]
It may be possible to display the static report in an iframe once the html is generated. This could be accompanied by a "download" button that downloads the html report. I'm not sure the the html can be held in an R object (using, perhaps, a `textConnection`) or if it must be a physical file. If it needs to be a physical file then it could potentially be saved using `tempdir` and visualized from there.

See this example for the physical file representation:
https://stackoverflow.com/questions/33020558/embed-iframe-inside-shiny-app

**Comment by atn38** [comment]
Thank you for the suggestion @wetlandscapes. This could be an option if the variable drop-down option (see #13) is not feasible.
