### ISSUE TITLE
print console message to UI with edi data fetching status

### ISSUE THREAD

**Issue by sheilasaia** [IMCR-Hackathon/ggplotgui#4]

**Comment by wetlandscapes** [comment]
I added a temporary message that says "Loading..." while a data package is downloading. Haven't figured out how to get the console to print to the app yet.

**Comment by wetlandscapes** [comment]
@sheilasaia would you be willing to give this a shot? Or are there other things you want to focus on? If it helps, I can provide an overview of the current "ingestion architecture" (for lack of a better phrase).

**Comment by sheilasaia** [comment]
I can work on this @wetlandscapes!

**Comment by wetlandscapes** [comment]
Well I had a major brain wave on how to do this as I was going to bed. My idea seems to have worked using the `shinyjs` package mentioned in the SO link above. The app now prints the download messages to the console as of fb9b402. Sorry if I'm getting in your way. I'll try to restrain myself from here on out. I just get really excited sometimes.
