### ISSUE TITLE
change sample data to displace dataset from edi

### ISSUE THREAD

**Issue by sheilasaia** [IMCR-Hackathon/ggplotgui#5]

**Comment by clnsmth** [comment]
Hi @sheilasaia, do you mean change the default sample data to a repository data package? If so, I will select a small one and add it to the R package as example data.

**Comment by wetlandscapes** [comment]
I actually already did this. I didn't realize this was an issue. Check the raw-data and data folders.

**Comment by sheilasaia** [comment]
Awesome, @wetlandscapes! Thanks for doing this. Can you please add the toy dataset to the package, @clnsmth?

**Comment by wetlandscapes** [comment]
It's already in the development branch of the package. From the top level of the package, the code for making the example dataset is in `data-raw/data_example.R`. That code was then used to make `data/data_example.rda`, which we can then access when the package loads.

**Comment by wetlandscapes** [comment]
I'm closing for now.

**Comment by clnsmth** [comment]
One thing to consider @wetlandscapes and @sheilasaia is whether the data_example.rda object enables demonstration of all the app features. If not, then we may want to consider adding the downloaded data package files to the R package.

**Comment by wetlandscapes** [comment]
Maybe I misunderstood? Could you elaborate?

**Comment by clnsmth** [comment]
Nope @wetlandscapes, I misunderstood. Using the `data_example.rda` object makes perfect sense for the default data package.
