### ISSUE TITLE
create development branch for shiny app

### ISSUE THREAD

**Issue by sheilasaia** [IMCR-Hackathon/ggplotgui#8]

**Comment by wetlandscapes** [comment]
I made a new branch, which folks can use for the development of the app. Feel free to branch the development branch for individual tasks. For more on branching and merging, I suggest the following page: https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging.

Here is the code I used to make the development branch, as well as the output generated (yes, my computer's name is CareBear). 
```sh
jjmercer@CareBear:/mnt/c/Projects/ggplotgui/R$ git checkout -b development
Switched to a new branch 'development'

jjmercer@CareBear:/mnt/c/Projects/ggplotgui/R$ git push origin development
Total 0 (delta 0), reused 0 (delta 0)
remote:
remote: Create a pull request for 'development' on GitHub by visiting:
remote:      https://github.com/IMCR-Hackathon/ggplotgui/pull/new/development
remote:
To https://github.com/IMCR-Hackathon/ggplotgui.git
 * [new branch]      development -> development
```

If you want to know what branch you are working on then you can use something like:
```sh
jjmercer@CareBear:/mnt/c/Projects/ggplotgui/R$ git branch
* development
  master
```

**Comment by sheilasaia** [comment]
@wetlandscapes can we close this?
