### ISSUE TITLE
brainstorm package name

### ISSUE THREAD

**Issue by sheilasaia** [IMCR-Hackathon/ggplotgui#9]

**Comment by wetlandscapes** [comment]
No matter what we come up with, I'm going to suggest we use the `available` package to determine if 1. the name is taken, and 2. if it is associated with an unintended concept (e.g., something found on urbandictionary.com). For an example of using `available`, check out Emil Hvitfeldt's package creation workflow: https://www.hvitfeldt.me/blog/usethis-workflow-for-package-development/#before-creation.

I'm also recommending we follow the naming conventions laid out by Hadley Wickham's "R Packages" book: http://r-pkgs.had.co.nz/package.html.

**Comment by wetlandscapes** [comment]
metabutter

**Comment by wetlandscapes** [comment]
metavisualization
metavis
metaviz

**Comment by wetlandscapes** [comment]
Basically, I like things that start with "meta" because it illustrates a thematic link between the packages. This could eventually be formalized by releasing a `metaverse` package.

**Comment by clnsmth** [comment]
[Link to list of candidate package names in Hackathon-Central-2019](https://github.com/IMCR-Hackathon/Hackathon-Central-2019/issues/14)

**Comment by CoastalPlainSoils** [comment]
Good thought with the urban dictionary! Wow! Didn't even think of that aspect of things.

**Comment by clnsmth** [comment]
Hi @sheilasaia, @wetlandscapes , @CoastalPlainSoils, @atn38, @jhp7e, @vanderbi, @lkuiucsb, @alesiahallmark, @ktoddbrown,

It's time to choose a name!

The way this is going to work:
-  (Now until - July 4) Propose 3 candidate names, each as it's own comment in this issue thread.
- (July 5-9) Add a thumbs up to your 3 favorite candidates. The top 3 will go to a run-off election.
- (July 10-11) Add a thumbs up to one of the top 3 candidates. The top candidate will be our package name.

**Comment by wetlandscapes** [comment]
metaviz

**Comment by wetlandscapes** [comment]
metabutter

**Comment by wetlandscapes** [comment]
metophile
(This one is actually dark humor. Rhymes with something bad. Don't vote for it.)

**Comment by ktoddbrown** [comment]
sedatr (Suitability Evaluator of DATa-packages in R)

**Comment by ktoddbrown** [comment]
sedatpacr (Suitability Evaluator of DATa-PACkages in R)

**Comment by ktoddbrown** [comment]
seguir (Suitability Evaluator GUI for R)

**Comment by atn38** [comment]
`dataPACMAN `
Data: (this) PACkage makes Assessment No problem

**Comment by atn38** [comment]
`PEASI` as in "easy-peasy"

data Package Evaluation made Accessible in Shiny Interface

**Comment by atn38** [comment]
`datapie`

Data Package Interface (for) Evaluation

with this and `metajam`, the `metaverse` is delicious

**Comment by jhp7e** [comment]
datavue

now you see it!

**Comment by jhp7e** [comment]
datashot

like a snapshot for data!

**Comment by jhp7e** [comment]
datapreview

what it does!

**Comment by clnsmth** [comment]
`repoRover` (repository rover)

Rover:
1.) Wanderer, roamer
2.) A vehicle for exploring the surface of an extraterrestrial body (such as the moon or Mars)
3.) Common name for dog

**Comment by clnsmth** [comment]
`dataRover`

**Comment by vanderbi** [comment]
enViznR  (Envisioner)

**Comment by clnsmth** [comment]
Below are the 3 finalists! Please vote for your favorite by July 11th (midnight).

**Comment by clnsmth** [comment]
`datapie`

Data Package Interface (for) Evaluation

with this and metajam, the metaverse is delicious 🍰 . Also, easy as pie.

**Comment by clnsmth** [comment]
`datavue`

now you see it!

**Comment by clnsmth** [comment]
`dataRover`

Rover:
1.) Wanderer, roamer
2.) A vehicle for exploring the surface of an extraterrestrial body (such as the moon or Mars)
3.) Common name for dog

**Comment by clnsmth** [comment]
`datapie` it is!
